#!/bin/bash

inputDir="$HOME/doc/study/"
#----------------------------
projectDir="$HOME/doc/projects/notes/"
xoppdir="${1:-$inputDir}"
pdfdir="$projectDir/root/pdf/"
pdf_files_data="$projectDir/root/data.json"


echo "$xoppdir =====> $pdfdir, $pdf_files_data"

# refreshing the pdf files (all "old/just update" pdf files were moved to /tmp/ dir)
mkdir -p /tmp/xopp-backup
mv "$pdfdir"/* /tmp/xopp-backup/  2>/dev/null

# Ensure the output directory exists
mkdir -p "$pdfdir"

# Iterate over xopp files
find "$xoppdir" -type f -name "*.xopp" | while read -r xopp_file; do
    # Check if the file exists
    if [ -e "$xopp_file" ]; then
        # Extracting the filename without path and extension
        filename=$(basename -- "$xopp_file")
        filename_noext="${filename%.xopp}"

        # Convert xopp to pdf
        xournalpp "$xopp_file" -p "$pdfdir$filename_noext.pdf"
        #echo "$xopp_file"  "$pdfdir$filename_noext.pdf"
    else
        echo "File not found: $xopp_file"
        exit 1;
    fi
done;

ls_output=$(ls -t -1 -v "$pdfdir" | jq -R -s 'split("\n")[:-1]')

if [ $? -eq 0 ]; then
    echo "$ls_output" > "$pdf_files_data"
    echo "Json Data generated Successfully." 
else
    echo "Error occurred while running ls command."
fi

# Flag to check if Git operations should be performed
echo "----------------------------------"
echo -n "Do you want 'git push' [y/N]: "
read q

if [[ $q = "y" ]]; then
    # Git operations
    git -C "$projectDir" add -A 
    echo -n "Commit [YYYY-MM-DD_HH:MM:SS]: "
    read commit
    git -C "$projectDir" commit -m "$(date +%Y-%m-%d_%I:%M:%S) : $commit"
    git -C "$projectDir" push
    echo "Git operations completed."
fi


